This is makeindex, version 2.16 [MiKTeX 22.10].
Scanning style file ./master.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file master.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (11 comparisons).
Generating output file master.acr....done (17 lines written, 0 warnings).
Output written in master.acr.
Transcript written in master.alg.
